language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip install --upgrade numpy scipy matplotlib pandas
  - pip install --upgrade scikit-learn
script:
  - python -m unittest discover -s test -p '*_test.py'
